# Generated by Django 6.0.5 on 2026-05-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('start_time', models.CharField(max_length=12)),
                ('end_time', models.CharField(max_length=12)),
                ('start_seconds', models.FloatField()),
                ('end_seconds', models.FloatField()),
                ('author_id', models.CharField(max_length=100)),
                ('last_active', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_time', 'id'],
                'indexes': [models.Index(fields=['author_id'], name='generator_t_author__6bde8e_idx')],
            },
        ),
    ]
