# Generated by Django 6.0.5 on 2026-05-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarytrack',
            name='text',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
