# Generated by Django 6.0.5 on 2026-05-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_alter_temporarytrack_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temporarytrack',
            options={'ordering': ['start_seconds', 'id']},
        ),
        migrations.AlterField(
            model_name='temporarytrack',
            name='end_seconds',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='temporarytrack',
            name='start_seconds',
            field=models.IntegerField(),
        ),
    ]
