# Generated by Django 6.0.5 on 2026-05-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_alter_temporarytrack_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarytrack',
            name='end_seconds',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='temporarytrack',
            name='start_seconds',
            field=models.FloatField(),
        ),
    ]
